CREATE TABLE IF NOT EXISTS renthouse_records (
  id BIGINT PRIMARY KEY,
  billMonth VARCHAR(20),
  startDate VARCHAR(20),
  endDate VARCHAR(20),
  totalBill DECIMAL(12,2) DEFAULT 0,
  publicElec DECIMAL(12,2) DEFAULT 0,
  baseFee DECIMAL(12,2) DEFAULT 0,
  billingKwh DECIMAL(12,3) DEFAULT 0,
  meterAprev DECIMAL(12,3) DEFAULT 0,
  meterAcurr DECIMAL(12,3) DEFAULT 0,
  meterA DECIMAL(12,3) DEFAULT 0,
  meterBprev DECIMAL(12,3) DEFAULT 0,
  meterBcurr DECIMAL(12,3) DEFAULT 0,
  meterB DECIMAL(12,3) DEFAULT 0,
  pricePerKwh DECIMAL(12,6) DEFAULT 0,
  costA DECIMAL(12,2) DEFAULT 0,
  costB DECIMAL(12,2) DEFAULT 0,
  period VARCHAR(50),
  readingDate VARCHAR(20),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS renthouse_tenants (
  id INT AUTO_INCREMENT PRIMARY KEY,
  data LONGTEXT,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS renthouse_drafts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  data LONGTEXT,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
