CREATE TABLE IF NOT EXISTS renthouse_water_records (
  id BIGINT PRIMARY KEY,
  billMonth VARCHAR(20),
  startDate VARCHAR(20),
  endDate VARCHAR(20),
  totalBill DECIMAL(12,2) DEFAULT 0,
  baseFee DECIMAL(12,2) DEFAULT 0,
  billingKwh DECIMAL(12,3) DEFAULT 0,
  wAprev DECIMAL(12,3) DEFAULT 0,
  wAcurr DECIMAL(12,3) DEFAULT 0,
  wBprev DECIMAL(12,3) DEFAULT 0,
  wBcurr DECIMAL(12,3) DEFAULT 0,
  readDate VARCHAR(20),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
